tutoWelcomeBundle_homepage:
    pattern:     /
    defaults: { _controller: tutoWelcomeBundle:Homepage:index }

homepage: 
    pattern:	/blog/articles/{page}
    defaults:	{ _controller: tutoWelcomeBundle:Homepage:index, page: 1 }
    requirements:
       page:   \d+
       _method: GET
