jul_platform_home:
    path:      /{page}
    defaults:  { _controller: JulTestBundle:Advert:index, page: 1 }
    requirements:
        page: \d*

jul_platform_view:
    path:      /advert/{id}
    defaults:  { _controller: JulTestBundle:Advert:view }
    requirements:
        id: \d+

jul_platform_add:
    path:      /add
    defaults:  { _controller: JulTestBundle:Advert:add }

jul_platform_edit:
    path:      /edit/{id}
    defaults:  { _controller: JulTestBundle:Advert:edit }
    requirements:
        id: \d+

jul_platform_delete:
    path:      /delete/{id}
    defaults:  { _controller: JulTestBundle:Advert:delete }
    requirements:
        id: \d+

jul_platform_view_slug:
    path:      /{year}/{slug}.{_format}
    defaults:  { _controller: JulTestBundle:Advert:viewSlug, _format: html }
    requirements:
        year: \d{4}
        format: html|xml		