oc_quizgen_homepage:
    path:     /
    defaults: { _controller: OCQuizgenBundle:Default:index }

oc_quizgen_add:
    path:    /add
    defaults: { _controller: OCQuizgenBundle:Default:add }

oc_quizgen_edit: 
    path:    /edit/{id}
    defaults: { _controller: OCQuizgenBundle:Default:edit }

oc_quizgen_duplicate: 
    path:    /duplicate/{id}
    defaults: { _controller: OCQuizgenBundle:Default:duplicate }

oc_quizgen_delete: 
    path:    /delete/{id}
    defaults: { _controller: OCQuizgenBundle:Default:delete }
    requirements:
         id: \d+

oc_quizgen_list:
    path:     /list
    defaults: { _controller: OCQuizgenBundle:Default:list }

oc_quizgen_view: 
    path:    /view/{id}
    defaults: { _controller: OCQuizgenBundle:Default:view }
    requirements:
         id: \d+
         
login:
    pattern:   /login

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout         
