oc_quizlaunch_index:
    path:     /launch/index
    defaults: { _controller: OCQuizlaunchBundle:Default:index }

oc_quizlaunch_pick:
    path:     /launch/pick/{id}
    defaults: { _controller: OCQuizlaunchBundle:Default:pick }
    requirements:
        id:   \d+


oc_quizlaunch_question:
    path:     /launch/question/{id}/{gamepin}/{idq}
    defaults: { _controller: OCQuizlaunchBundle:Default:launchquestion }
    requirements:
        id:   \d+
        gamepin:   \d+
        idq:   \d+
