oc_quizlaunch_index:
    path:     /
    defaults: { _controller: OCQuizlaunchBundle:Default:index }

oc_quizlaunch_pick:
    path:     /{id}
    defaults: { _controller: OCQuizlaunchBundle:Default:pick }
    requirements:
        id:   \d+

oc_quizlaunch_question:
    path:     /question/{id}/{gamepin}/{idq}
    defaults: { _controller: OCQuizlaunchBundle:Default:launchquestion }
    requirements:
        id:   \d+
        gamepin:   \d+
        idq:   \d+

oc_quizlaunch_score:
    path:     /score/{id}/{gamepin}/{idq}
    defaults: { _controller: OCQuizlaunchBundle:Default:resQuestion }
    requirements:
        id:   \d+
        gamepin:   \d+
        idq:   \d+

