oc_quizdis_select:
    path:     /
    defaults: { _controller: OCQuizdisBundle:Default:index }

oc_quizdis_pseudo:
    path:     /pseudo/{gamepin}
    defaults: { _controller: OCQuizdisBundle:Default:pseudo }
    requirements:
         gamepin: \d+

oc_quizdis_play:
    path:     /{gamepin}
    defaults: { _controller: OCQuizdisBundle:Default:play }
    requirements:
         gamepin: \d+