oc_quizdis_select:
    path:     /select
    defaults: { _controller: OCQuizdisBundle:Default:index }

oc_quizdis_play:
    path:     /play/{gamepin}
    defaults: { _controller: OCQuizdisBundle:Default:play }
    requirements:
         gamepin: \d+